spring.application.name=demo
# MongoDB Atlas - Connection
spring.mongodb.uri=mongodb+srv://bookclub_user:admin@cluster0.n7el5gk.mongodb.net/bookclub?retryWrites=true&w=majority
spring.mongodb.database=bookclub